### ISSUE TITLE
Search using GET?

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-elasticsearch#14]
As discussed over IRC, it's a little strange/uncommon to use POST requests to read from the server. It seems we're just porting ES' behavior here, but we may want to revisit that strategy. A `GET` would make more sense to me.

**Comment by Natim** [comment]
I totally agree with you here.
I think ES is using POST in order to be able to provide a JSON body.
There are some URI length limitations and you cannot provide a body with GET.
While the body of the search can be quite long with ES.

That's a draw back I would be willing to take for this plugin especially if we want to be compatible with ES behavior here.
